// Vendors every emoji a post actually uses into public/emoji/, so the repo
// carries a few KB instead of the 16 MB of the two full sets.
//
//   Unicode  🤔  -> public/emoji/unicode/1f914.png
//   Shortcode :blobcheer: -> public/emoji/blob/blobcheer.png
//
// Run after adding an emoji to a post: yarn sync-emoji
import { execFileSync } from 'child_process'
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'fs'
import path from 'path'
import { codepointName } from '../lib/rehype-emoji.mjs'

const CONTENT_DIR = path.join(process.cwd(), 'data')
const EMOJI_DIR = path.join(process.cwd(), 'public', 'emoji')
const UNICODE_DIR = path.join(EMOJI_DIR, 'unicode')
const BLOB_DIR = path.join(EMOJI_DIR, 'blob')

// Blobmoji ships its PNGs only inside a release asset, so the archive is cached
// under node_modules (already gitignored) rather than re-downloaded each run.
const BLOBMOJI_RELEASE = 'https://github.com/C1710/blobmoji/releases/download/v15.0/png.zip'
const BLOBMOJI_CACHE = path.join(process.cwd(), 'node_modules', '.cache', 'blobmoji')

// The blobs.gg set, where each file is named after its Discord shortcode.
const BLOB_RAW = 'https://raw.githubusercontent.com/Raymo111/emoji/master/docs'

const EMOJI_OR_SHORTCODE = /(\p{RGI_Emoji})|:([a-zA-Z0-9_+\-]+):/gv

function mdxFiles(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) return mdxFiles(full)
    return entry.name.endsWith('.mdx') || entry.name.endsWith('.md') ? [full] : []
  })
}

function collectUsage() {
  const unicode = new Map() // codepoint name -> the emoji itself, for reporting
  const shortcodes = new Set()

  for (const file of mdxFiles(CONTENT_DIR)) {
    for (const [, emoji, shortcode] of readFileSync(file, 'utf8').matchAll(EMOJI_OR_SHORTCODE)) {
      if (emoji) unicode.set(codepointName(emoji), emoji)
      else shortcodes.add(shortcode)
    }
  }
  return { unicode, shortcodes }
}

function ensureBlobmojiCache() {
  const pngDir = path.join(BLOBMOJI_CACHE, 'png')
  if (existsSync(pngDir)) return pngDir

  console.log('Downloading the Blobmoji PNG set (~13 MB, cached under node_modules)…')
  mkdirSync(BLOBMOJI_CACHE, { recursive: true })
  const zip = path.join(BLOBMOJI_CACHE, 'png.zip')
  execFileSync('curl', ['-sL', '-o', zip, BLOBMOJI_RELEASE])
  execFileSync('unzip', ['-q', '-o', zip, '-d', BLOBMOJI_CACHE])
  return pngDir
}

async function syncUnicode(unicode) {
  const missing = [...unicode].filter(
    ([name]) => !existsSync(path.join(UNICODE_DIR, `${name}.png`))
  )
  if (missing.length === 0) return { added: 0, absent: [] }

  const pngDir = ensureBlobmojiCache()
  mkdirSync(UNICODE_DIR, { recursive: true })

  const absent = []
  let added = 0
  for (const [name, emoji] of missing) {
    const source = path.join(pngDir, `emoji_u${name}.png`)
    if (!existsSync(source)) {
      absent.push(`${emoji} (U+${name.toUpperCase()})`)
      continue
    }
    copyFileSync(source, path.join(UNICODE_DIR, `${name}.png`))
    console.log(`  + ${emoji}  unicode/${name}.png`)
    added += 1
  }
  return { added, absent }
}

async function syncBlobs(shortcodes) {
  const missing = [...shortcodes].filter((name) => !existsSync(path.join(BLOB_DIR, `${name}.png`)))
  if (missing.length === 0) return { added: 0, absent: [] }

  mkdirSync(BLOB_DIR, { recursive: true })

  const absent = []
  let added = 0
  for (const name of missing) {
    const response = await fetch(`${BLOB_RAW}/${name}.png`)
    if (!response.ok) {
      // Almost always a plain colon-wrapped word rather than a real shortcode,
      // so this is a note, not a failure — it stays as text in the post.
      absent.push(name)
      continue
    }
    writeFileSync(path.join(BLOB_DIR, `${name}.png`), Buffer.from(await response.arrayBuffer()))
    console.log(`  + :${name}:  blob/${name}.png`)
    added += 1
  }
  return { added, absent }
}

// public/emoji is generated, so it should mirror what the posts actually use —
// otherwise an emoji dropped from a post lingers in the repo forever.
function prune(dir, keep) {
  if (!existsSync(dir)) return []
  const stale = readdirSync(dir)
    .filter((file) => file.endsWith('.png'))
    .filter((file) => !keep.has(path.basename(file, '.png')))

  for (const file of stale) {
    rmSync(path.join(dir, file))
    console.log(`  - ${path.basename(dir)}/${file}`)
  }
  return stale
}

function writeAttribution() {
  mkdirSync(EMOJI_DIR, { recursive: true })
  writeFileSync(
    path.join(EMOJI_DIR, 'README.md'),
    `# Vendored emoji

Generated by \`yarn sync-emoji\` — do not edit by hand.

- \`unicode/\` — [C1710/blobmoji](https://github.com/C1710/blobmoji) (Apache-2.0),
  Google's original blob designs for standard Unicode emoji.
- \`blob/\` — the [blobs.gg](https://blobs.gg/) community set via
  [Raymo111/emoji](https://github.com/Raymo111/emoji) (Apache-2.0), the custom
  \`:shortcode:\` blobs used on Discord.

Only emoji that appear in a post are vendored; the full sets are ~16 MB.
`
  )
}

async function main() {
  const { unicode, shortcodes } = collectUsage()
  console.log(`Found ${unicode.size} unicode emoji and ${shortcodes.size} shortcode candidates.\n`)

  const uni = await syncUnicode(unicode)
  const blob = await syncBlobs(shortcodes)

  // Prune against the names we could actually resolve, so a typo'd shortcode
  // does not drag a real emoji out of the repo with it.
  const staleUnicode = prune(UNICODE_DIR, new Set(unicode.keys()))
  const staleBlobs = prune(
    BLOB_DIR,
    new Set([...shortcodes].filter((n) => !blob.absent.includes(n)))
  )
  writeAttribution()

  console.log(`\nVendored ${uni.added + blob.added} new file(s).`)
  if (staleUnicode.length + staleBlobs.length > 0) {
    console.log(
      `Pruned ${staleUnicode.length + staleBlobs.length} file(s) no longer used by any post.`
    )
  }
  if (uni.absent.length > 0) {
    console.log(
      `No blob design exists for: ${uni.absent.join(', ')} — will fall back to the system font.`
    )
  }
  if (blob.absent.length > 0) {
    console.log(
      `Not a known blob shortcode: ${blob.absent.map((n) => `:${n}:`).join(', ')} — left as plain text.`
    )
  }
}

main().catch((err) => {
  console.error(err.message)
  process.exit(1)
})
